#pragma once

#define TEST_PIN_NO		33

#define MSG_INIT					0
#define MSG_CHECK_PIN_NO			1
#define MSG_CHECK_PIN_ERR			2
#define MSG_CHECK_PIN_DISCORRECT	3

#define MSG_CARD_MAIN				4
#define MSG_CARD_MAIN_ERR			5

#define MSG_CARD_SHOW_BALANCE		6

#define MSG_CARD_DEPOSIT			7
#define MSG_CARD_DEPOSIT_ERR		8
#define MSG_CARD_WITHDRAW			9
#define MSG_CARD_WITHDRAW_ERR		10

typedef enum {
	MENU_INIT = 0,
	//MENU_WAIT_CARD_INTPUT = 1,
	MENU_CHECK_PIN_NUM = 2,
	MENU_CARD_MAIN = 3,
	MENU_CARD_SHOW_BALANCE = 4,
	MENU_CARD_DEPOSIT = 5,
	MENU_CARD_DEPOSIT_PROCESS = 6,
	MENU_CARD_WITHDRAW = 7,
	MENU_CARD_WITHDRAW_PROCESS = 8
}_menu;